// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vigtaqmmyxuzfwrcuqss.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZpZ3RhcW1teXh1emZ3cmN1cXNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0MzcwMjMsImV4cCI6MjA2NDAxMzAyM30.OE7jUefyjb2FzTAuUNmEitVNMaQGbpoGiPjy3J2MyL4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);